name: Firefly Chat Commit

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Was soll der Bot im Code tun?"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    env:
      FIREFLY_BOT_TOKEN: ${{ secrets.FIREFLY_BOT_TOKEN }}
      OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout (ohne Default-Creds)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Git-User setzen (firefly-bot)
        run: |
          git config user.name "firefly-bot"
          git config user.email "firefly-bot@users.noreply.github.com"

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Show versions
        run: node -v && npm -v

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Aider installieren (optional)
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install "aider-chat>=0.86"

      - name: Code-Änderungen aus Task erzeugen (optional)
        if: ${{ env.OPENAI_API_KEY != '' }}
        shell: bash
        run: |
          set -euo pipefail
          MSG_FILE="$(mktemp)"
          # Task-Text wörtlich in Datei schreiben (keine Expansion):
          cat > "$MSG_FILE" <<'TASK'
          ${{ inputs.task }}
          TASK
          # Inhalt sicher als ein Argument an Aider übergeben:
          aider --yes --no-gitignore --commit --message "$(cat "$MSG_FILE")" || true

      - name: Commit (falls Änderungen)
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "bot: ${{ inputs.task }}"
          else
            echo "No changes to commit."
          fi

      - name: Branch pushen und PR erstellen (nur wenn Änderungen und Token)
        if: ${{ env.FIREFLY_BOT_TOKEN != '' }}
        env:
          GH_TOKEN: ${{ github.token }}   # für gh pr create
        shell: bash
        run: |
          set -euo pipefail
          # Nur wenn es Commit(s) gibt
          if [ -z "$(git log origin/main..HEAD --oneline || true)" ]; then
            echo "No new commits; skipping PR creation."
            exit 0
          fi

          BRANCH="bot/${GITHUB_RUN_ID}"
          git checkout -B "$BRANCH"

          # Push mit Bot-PAT
          git remote set-url origin https://x-access-token:${FIREFLY_BOT_TOKEN}@github.com/${{ github.repository }}.git
          git push -u origin "$BRANCH"

          # PR mit Actions-Token
          gh pr create \
            --title "bot: ${{ inputs.task }}" \
            --body "Automated PR by firefly-bot\n\nTask:\n${{ inputs.task }}" \
            --head "$BRANCH" \
            --base "main" \
            --repo "${{ github.repository }}"

      - name: Hinweis, falls kein Bot-Token gesetzt ist
        if: ${{ env.FIREFLY_BOT_TOKEN == '' }}
        run: echo "::warning:: FIREFLY_BOT_TOKEN secret fehlt – Push/PR übersprungen."
