name: PR - Fix TradingEngine

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fix-tradingengine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Apply fix
        run: |
          mkdir -p src/engine
          cat > src/engine/tradingEngine.ts <<'EOF'
import { applyRules } from "../rules";

export type Action = "buy" | "sell" | "hold";

export interface TradeDecision {
  action: Action;
  reason?: string;
  size?: number;
}

function isAction(x: unknown): x is Action {
  return x === "buy" || x === "sell" || x === "hold";
}

export function runTradingEngine(): TradeDecision {
  const outcome: unknown = applyRules({});
  const action: Action =
    isAction(outcome)
      ? outcome
      : (outcome as { action?: Action })?.action ?? "hold";

  return {
    action,
    reason: "stub-decision",
    size: 0,
  };
}
EOF

      - name: Commit
        run: |
          git config user.name "firefly-bot"
          git config user.email "firefly-bot@users.noreply.github.com"
          git checkout -b fix/tradingengine
          git add src/engine/tradingEngine.ts
          git commit -m "fix(engine): robust runTradingEngine type handling"

      - name: Push branch
        env:
          FIREFLY_BOT_TOKEN: ${{ secrets.FIREFLY_BOT_TOKEN }}
        run: |
          git remote set-url origin "https://x-access-token:${FIREFLY_BOT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push -u origin fix/tradingengine --force-with-lease

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.FIREFLY_BOT_TOKEN }}
        run: |
          gh pr create \
            --title "fix(engine): runTradingEngine robust type handling" \
            --body "Fixes YAML syntax, closes Here-Doc, ensures Action type safety." \
            --base main \
            --head fix/tradingengine || echo "PR may already exist"
